In [1]:
import os
import sys
sys.path.append(os.path.abspath(os.path.join('..')))

from src.dataset import load_adult_data

In [2]:
X, y, s = load_adult_data( path= "/data/han/data/fairness/adult", sensitive_attribute="sex" )

In [3]:
X

,age,education_num,capital_gain,capital_loss,hours_per_week,workclass_Federal-gov,workclass_Local-gov,workclass_Private,workclass_Self-emp-inc,workclass_Self-emp-not-inc,...,education_HS-grad,education_Masters,education_Preschool,education_Prof-school,education_Some-college,race_Amer-Indian-Eskimo,race_Asian-Pac-Islander,race_Black,race_Other,race_White
0,39.0,13.0,2174.0,0.0,40.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,50.0,13.0,0.0,0.0,13.0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
2,38.0,9.0,0.0,0.0,40.0,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,1
3,53.0,7.0,0.0,0.0,40.0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
4,28.0,13.0,0.0,0.0,40.0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16275,33.0,13.0,0.0,0.0,40.0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
16276,39.0,13.0,0.0,0.0,36.0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
16278,38.0,13.0,0.0,0.0,50.0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
16279,44.0,13.0,5455.0,0.0,40.0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
16280,35.0,13.0,0.0,0.0,60.0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1

In [4]:
X.dtypes

age                        float32
education_num              float32
capital_gain               float32
capital_loss               float32
hours_per_week             float32
                            ...
race_Amer-Indian-Eskimo      uint8
race_Asian-Pac-Islander      uint8
race_Black                   uint8
race_Other                   uint8
race_White                   uint8
Length: 101, dtype: object